Repository falcosecurity/client-py, pull requests merged in 2020-02, with the labels that each got.

#17 update: adding leodido to approvers
  OWNERS
Labels: approved, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#21 Add json output format, add example, cleanup
  README.md
  examples/get_events.py
  falco/client.py
  falco/domain/response.py
  requirements-dev.txt
  requirements.txt
  tests/conftest.py
  tests/domain/test_request.py
  tests/domain/test_response.py
Labels: approved, area/client, area/examples, dco-signoff: yes, kind/cleanup, kind/feature, lgtm, release-note, size/L

#23 update: propose @mmat11 as approver/reviewer
  OWNERS
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#27 build: fetch proto files from Falco's master
  Makefile
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#31 CI: install dependencies once
  .github/workflows/ci.yml
  falco/__version__.py
Labels: approved, area/client, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS
